export const geminiCliReviewOutputFormat = "json";
export const geminiCliReviewApprovalMode = "plan";
export const geminiCliReviewPolicyFileName = "gemini-review-policy.toml";
export const geminiCliReviewTrustedFoldersFileName = "gemini-trusted-folders.json";
export const geminiCliReviewDisabledExtensions = "none";
export const geminiCliReviewMcpAllowlist = "";
export const geminiCliTrustWorkspaceEnvVar = "GEMINI_CLI_TRUST_WORKSPACE";
export const geminiCliTrustedFoldersPathEnvVar = "GEMINI_CLI_TRUSTED_FOLDERS_PATH";
export const geminiCliSkipTrustFlag = "--skip-trust";

export const geminiCliAllowedReviewTools = [
  "read_file",
  "list_directory",
  "glob",
  "grep_search",
  "search_file_content",
] as const;

export const geminiCliReviewPolicyCliFlags = [
  "--prompt",
  geminiCliSkipTrustFlag,
  "--output-format",
  "--approval-mode",
  "--policy",
  "--admin-policy",
  "--allowed-mcp-server-names",
  "--extensions",
] as const;

export const geminiCliReviewPolicyReason =
  "Diffwarden Gemini reviews may only read, list, glob, and grep files.";

export function geminiCliReviewPolicyToml(): string {
  return `# Generated by Diffwarden for Gemini CLI reviews.
[[rule]]
toolName = "*"
mcpName = "*"
decision = "deny"
priority = 999
denyMessage = ${JSON.stringify(geminiCliReviewPolicyReason)}

[[rule]]
toolName = [${geminiCliAllowedReviewTools.map((tool) => JSON.stringify(tool)).join(", ")}]
decision = "allow"
priority = 998

[[rule]]
toolName = "*"
decision = "deny"
priority = 997
denyMessage = ${JSON.stringify(geminiCliReviewPolicyReason)}
`;
}

export function geminiCliReviewPolicyMetadata(): Record<string, unknown> {
  return {
    geminiApprovalMode: geminiCliReviewApprovalMode,
    geminiPolicyMode: "policy-and-admin-policy",
    geminiPolicyScope: "all-modes",
    geminiAllowedTools: [...geminiCliAllowedReviewTools],
    geminiMcpAllowlist: "none",
    geminiExtensions: geminiCliReviewDisabledExtensions,
    geminiSandboxMode: "not-enabled-by-default",
    geminiWorkspaceTrust: "isolated-session-skip-trust",
    geminiTrustEnv: "inherited-trust-workspace-unset",
    geminiTrustedFolders: "empty-temp-file",
  };
}
